pipeline {
     agent {label 'docker-agent'}
     stages {
          stage("Compile") {
               steps {
                    sh "./gradlew compileJava"
               }
          }
          stage("Unit test") {
               steps {
                    sh "./gradlew test"
               }
          }
          // Should only activate when .java is changed
          stage ('Code Coverage') {
               when {
                    changeset "**/*.java"  // Triggers only of .java files are changes
               }
               steps {
                    sh "./gradlew jacocoTestReport"
                    sh "./gradlew jacocoTestCoverageVerification"
               }
               post {
                    success {
                         echo "pipeline ran perfectly"
                    }
                    failure {
                         echo "pipeline failure"
                    }
               }
          }
          stage("Static code analysis") {
               when {
                    changeset "**/*.java"  // Triggers only of .java files are changes
               }
               steps {
                    sh "./gradlew checkstyleMain"
                    publishHTML (
                         target: [
                              reportDir: 'Chapter08/sample1/build/reports/checkstyle',   
                              reportFiles: 'main.html',reportName: "jacoco checkstyle main report"
                              ]
                         )
               }
               post {
                    success {
                         echo "pipeline ran perfectly"
                    }
                    failure {
                         echo "pipeline failure"
                    }
               }
          }

          stage("Checkstyle Test") {
               when {
                  changeset "**/*.java"  // Triggers only of .java files are changes
               }
               steps {  
                    sh "./gradlew checkstyleTest"

                    publishHTML (
                         target: [
                              reportDir: 'Chapter08/sample1/build/reports/checkstyle',   
                              reportFiles: 'test.html',reportName: "jacoco checkstyle"
                              ]
                         )
               }
               post {
                    success {
                         echo "pipeline ran perfectly"
                    }
                    failure {
                         echo "pipeline failure"
                    }
               }
          }

          stage("Package") {
               steps {
                    sh "./gradlew build"
               }
          }

          stage("Docker build") {
               steps {
                    sh "docker build -t leszko/calculator:${BUILD_TIMESTAMP} ."
               }
          }

          stage("Docker login") {
               steps {
                    withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker-hub-credentials',
                               usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                         sh "docker login --username $USERNAME --password $PASSWORD"
                    }
               }
          }

          stage("Docker push") {
               steps {
                    sh "docker push leszko/calculator:${BUILD_TIMESTAMP}"
               }
          }

          stage("Update version") {
               steps {
                    sh "sed  -i 's/{{VERSION}}/${BUILD_TIMESTAMP}/g' calculator.yaml"
               }
          }
          
          stage("Deploy to staging") {
               steps {
                    sh "kubectl config use-context staging"
                    sh "kubectl apply -f hazelcast.yaml"
                    sh "kubectl apply -f calculator.yaml"
               }
          }

          stage("Acceptance test") {
               steps {
                    sleep 60
                    sh "chmod +x acceptance-test.sh && ./acceptance-test.sh"
               }
          }

          stage("Release") {
               steps {
                    sh "kubectl config use-context production"
                    sh "kubectl apply -f hazelcast.yaml"
                    sh "kubectl apply -f calculator.yaml"
               }
          }
          stage("Smoke test") {
              steps {
                  sleep 60
                  sh "chmod +x smoke-test.sh && ./smoke-test.sh"
              }
          }

     }
}