pipeline {
     agent {label 'docker-agent'}
     stages {
          stage("Compile") {
               steps {
                    dir('Chapter08/sample1') {
                         sh "./gradlew compileJava"
                    }
               }
          }
          stage("Unit test") {
               steps {
                    dir('Chapter08/sample1') {
                         sh "./gradlew test"
                    }
               }
          }
          // Should only activate when .java is changed
          stage ('Code Coverage') {
               when {
                    changeset "**/*.java"
               }
               steps {
                    dir('Chapter08/sample1') {
                         sh "./gradlew jacocoTestReport"
                         sh "./gradlew jacocoTestCoverageVerification"
                    }
               }
          }
          stage("Static code analysis") {
               when {
                    changeset "**/*.java"  // Triggers only of .java files are changes
               }
               steps {
                    dir('Chapter08/sample1') {
                         sh "./gradlew checkstyleMain"
                    publishHTML (
                         target: [
                              reportDir: 'build/reports/checkstyle',   
                              reportFiles: 'main.html',reportName: "jacoco checkstyle main report"
                              ]
                         )
                    }
               }
          }

          stage("Checkstyle Test") {
               when {
                  changeset "**/*.java"  // Triggers only of .java files are changes
               }
               steps {  
                    dir('Chapter08/sample1') {
                         sh "./gradlew checkstyleTest"
                         publishHTML (
                              target: [
                                   reportDir: 'build/reports/checkstyle',   
                                   reportFiles: 'test.html',reportName: "jacoco checkstyle"
                                   ]
                         )
                    }
               }
          }

          stage("Package") {
               steps {
                    dir('Chapter08/sample1') {
                         sh "./gradlew build"
                    }
               }
          }

          stage("Docker build") {
               steps {
                    dir('Chapter08/sample1') {
                         sh "docker build -t echo326312/calculator:${BUILD_TIMESTAMP} ."
                    }
               }
          }

          stage("Docker login") {
               steps {
                    dir('Chapter08/sample1') {
                         withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker-hub-credentials',
                                   usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                              sh "docker login --username $USERNAME --password $PASSWORD"
                              }
                    }
               }
          }

          stage("Docker push") {
               steps {
                    dir('Chapter08/sample1') {
                         sh "docker push echo326312/calculator:${BUILD_TIMESTAMP}"
                    }
               }
          }

          stage("Update version") {
               steps {
                    dir('Chapter08/sample1') {
                         sh "sed  -i 's/{{VERSION}}/${BUILD_TIMESTAMP}/g' calculator.yaml"
                    }
               }
          }
          
          stage("Deploy to staging") {
               steps {
                    dir('Chapter08/sample1') {
                         sh "kubectl config use-context staging"
                         sh "kubectl apply -f hazelcast.yaml"
                         sh "kubectl apply -f calculator.yaml"
                    }
               }
          }

          stage("Acceptance test") {
               steps {
                    dir('Chapter08/sample1') {
                         sleep 60
                         sh "chmod +x acceptance-test.sh && ./acceptance-test.sh"
                    }
               }
          }

          stage("Release") {
               steps {
                    dir('Chapter08/sample1') {
                         sh "kubectl config use-context production"
                         sh "kubectl apply -f hazelcast.yaml"
                         sh "kubectl apply -f calculator.yaml"
                    }
               }
          }
          stage("Smoke test") {
              steps {
               dir('Chapter08/sample1'){
                  sleep 60
                  sh "chmod +x smoke-test.sh && ./smoke-test.sh"
               }
              }
          }

     }
     post {
          success { echo "pipeline ran perfectly" }
          failure { echo "pipeline failure" }
          }
}